question_data = [
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "French is an official language in Canada.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Bulls are attracted to the color red.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "When you cry in space, your tears stick to your face.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "A pasodoble is a type of Italian pasta sauce.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The mitochondria is the powerhouse of the cell.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Jingle Bells was originally meant for Thanksgiving",
     "correct_answer": "True", "incorrect_answers": ["False"]}]

# question_data = [
#     {"category": "Entertainment: Film",
#      "type": "boolean",
#      "difficulty": "easy",
#      "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "George Lucas directed the entire original Star Wars trilogy.",
#      "correct_answer": "False", "incorrect_answers": ["True"]}]


#
# {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car,"
#              " you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
#      "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]
